# Generated by Django 6.1.1 on 2026-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_starter_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dept',
            field=models.CharField(choices=[('', ''), ('account_mgt', 'Account Management'), ('calibrate', 'Calibrate'), ('clean_room', 'Clean Room'), ('customer_service', 'Customer Service'), ('data_center', 'Data Center'), ('general', 'General'), ('general_it', 'General IT'), ('inductions', 'Inductions'), ('marine', 'Marine'), ('marketing', 'Marketing'), ('qa', 'QA'), ('sales', 'Sales'), ('shipping', 'Shipping And Receiving')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('email', 'Email'), ('phone', 'Phone'), ('integer', 'Whole number'), ('decimal', 'Decimal number'), ('date', 'Date'), ('checkbox', 'Checkbox (required means checked)'), ('dropdown', 'Dropdown'), ('multiple_choice', 'Multiple choice')], default='text', max_length=24),
        ),
    ]
