# Generated by Django 6.1.1 on 2026-09-23 17:22

import helpdesk.models.definitions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticket_dept_alter_ticketfield_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_Name', models.CharField(max_length=150)),
                ('Download Website', models.URLField(blank=True, null=True)),
                ('File / Folder Path', models.FilePathField(allow_folders=True, blank=True, null=True, path=helpdesk.models.definitions.Software_file_path)),
            ],
            options={
                'verbose_name_plural': 'Approved Software Files',
                'ordering': ['software_Name'],
            },
        ),
    ]
