# Generated by Django 6.1.1 on 2026-09-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_approvedsoftware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedsoftware',
            name='File / Folder Path',
        ),
        migrations.AddField(
            model_name='approvedsoftware',
            name='file_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
