# Generated by Django 6.1.1 on 2026-09-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_remove_approvedsoftware_file_folder_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hardware Name', models.CharField(max_length=150)),
            ],
        ),
    ]
