# Generated by Django 6.1.1 on 2026-09-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_currenthardware'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currenthardware',
            old_name='Hardware Name',
            new_name='hardware_Name',
        ),
    ]
