# Generated by Django 6.1.1 on 2026-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_rename_hardware_name_currenthardware_hardware_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True),
        ),
    ]
